version: '3.8'

services:

  prometheus:
    build:
      context: ./prometheus
      dockerfile: dockerfile
    user: root # required for data persistence
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    environment:
      - FLASHCASTR_API_TARGET=${FLASHCASTR_API_TARGET}
      - FLASH_ENGINE_TARGET=${FLASH_ENGINE_TARGET}
      - DATABASE_ENGINE_TARGET=${DATABASE_ENGINE_TARGET}
      - IMAGE_ENGINE_TARGET=${IMAGE_ENGINE_TARGET}
      - NEYNAR_ENGINE_TARGET=${NEYNAR_ENGINE_TARGET}

  loki:
    build:
      context: ./loki
      dockerfile: dockerfile
    user: root # required for data persistence
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki

  tempo:
    build:
      context: ./tempo
      dockerfile: dockerfile
    user: root # required for data persistence
    ports:
      - "3200:3200" # http server for querying
      - "4317:4317" # grpc server for ingest
      - "4318:4318" # http server for ingest
    volumes:
      - tempo_data:/var/tempo

  loki-gateway:
    build:
      context: ./loki-gateway
      dockerfile: Dockerfile
    ports:
      - "3101:3101"
    environment:
      - LOKI_BASIC_AUTH_USER=${LOKI_BASIC_AUTH_USER}
      - LOKI_BASIC_AUTH_HASH=${LOKI_BASIC_AUTH_HASH}
      - LOKI_UPSTREAM=loki:3100
    depends_on:
      - loki

  prom-gateway:
    build:
      context: ./prom-gateway
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    environment:
      - PROM_BASIC_AUTH_USER=${PROM_BASIC_AUTH_USER}
      - PROM_BASIC_AUTH_HASH=${PROM_BASIC_AUTH_HASH}
      - PROM_UPSTREAM=prometheus:9090
    depends_on:
      - prometheus

  tempo-gateway:
    build:
      context: ./tempo-gateway
      dockerfile: Dockerfile
    ports:
      - "3201:3201"
    environment:
      - TEMPO_BASIC_AUTH_USER=${TEMPO_BASIC_AUTH_USER}
      - TEMPO_BASIC_AUTH_HASH=${TEMPO_BASIC_AUTH_HASH}
      - TEMPO_UPSTREAM=tempo:3200
    depends_on:
      - tempo

  grafana:
    build:
      context: ./grafana
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword123
      - GF_DEFAULT_INSTANCE_NAME=Grafana
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel
      - LOKI_INTERNAL_URL=http://loki:3100
      - PROMETHEUS_INTERNAL_URL=http://prometheus:9090
      - TEMPO_INTERNAL_URL=http://tempo:3200

volumes:
  prometheus_data:
  loki_data:
  grafana_data:
  tempo_data:
