ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

USER root

# Install envsubst (part of gettext)
RUN apk add --no-cache gettext

# Copy the template config
COPY prom.yml /etc/prometheus/prom.yml.template

# Create entrypoint script
RUN printf '#!/bin/sh\\nenvsubst < /etc/prometheus/prom.yml.template > /etc/prometheus/prom.yml\\nexec /bin/prometheus "$@"\\n' > /entrypoint.sh && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]
