ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

USER root

# Copy the template config
COPY prom.yml /etc/prometheus/prom.yml.template

# Create entrypoint script using sed for variable substitution
RUN printf '#!/bin/sh\nset -e\nsed -e "s|\${INVADERS_BOT_TARGET}|${INVADERS_BOT_TARGET}|g" -e "s|\${INVADERS_CONSUMER_TARGET}|${INVADERS_CONSUMER_TARGET}|g" -e "s|\${FLASHCASTR_API_TARGET}|${FLASHCASTR_API_TARGET}|g" /etc/prometheus/prom.yml.template > /etc/prometheus/prom.yml\nexec /bin/prometheus "$@"\n' > /entrypoint.sh && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]
