global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flashcastr-api"
    static_configs:
      - targets: ["${FLASHCASTR_API_TARGET}"]
    metrics_path: /metrics

  - job_name: "flash-engine"
    static_configs:
      - targets: ["${FLASH_ENGINE_TARGET}"]
    metrics_path: /metrics

  - job_name: "database-engine"
    static_configs:
      - targets: ["${DATABASE_ENGINE_TARGET}"]
    metrics_path: /metrics

  - job_name: "image-engine"
    static_configs:
      - targets: ["${IMAGE_ENGINE_TARGET}"]
    metrics_path: /metrics

  - job_name: "neynar-engine"
    static_configs:
      - targets: ["${NEYNAR_ENGINE_TARGET}"]
    metrics_path: /metrics
